@baseURL=http://localhost:3000/pessoas
@login=http://localhost:3000/auth/login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZnVuY2FvIjoiQXRlbmRlbnRlIiwiaWF0IjoxNzc4NTMyNjk0LCJleHAiOjE3Nzg1MzYyOTR9.hGTFat1IFZhmT6mGlNUP03pICAFzvx0HU41JPVlFloQ

### login
POST {{login}}
Content-Type: application/json

{
    "cpf":"96145395001",
    "senha":"senha123"
}

### lista médicos e pacientes
GET {{baseURL}}/lista
Authorization: Bearer {{token}}

### lista médico específico
GET {{baseURL}}/lista/4
Authorization: Bearer {{token}}

### lista paciente específico
GET {{baseURL}}/lista/6
Authorization: Bearer {{token}}

### NÃO lista admin
GET {{baseURL}}/lista/1
Authorization: Bearer {{token}}

### NÃO lista atendente
GET {{baseURL}}/lista/3
Authorization: Bearer {{token}}

### lista a si mesmo
GET {{baseURL}}/lista/2
Authorization: Bearer {{token}}

### ativa médico específico
PUT  {{baseURL}}/ativar/4
Authorization: Bearer {{token}}

### desativa médico específico
PUT  {{baseURL}}/desativar/4
Authorization: Bearer {{token}}

### ativa paciente específico
PUT {{baseURL}}/ativar/6
Authorization: Bearer {{token}}

### desativa paciente específico
PUT {{baseURL}}/desativar/6
Authorization: Bearer {{token}}

### REVER ESTE TESTE
### ativa / desativa a si mesmo?

### NÃO ativa admin
PUT {{baseURL}}/ativar/1
Authorization: Bearer {{token}}

### NÃO desativa admin
PUT {{baseURL}}/desativar/1
Authorization: Bearer {{token}}

### NÃO ativa atendente
PUT {{baseURL}}/ativar/3
Authorization: Bearer {{token}}

### NÃO desativa atendente
PUT {{baseURL}}/desativar/3
Authorization: Bearer {{token}}

### altera médico específico
PUT {{baseURL}}/atualizar/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cpf": "03209484040",
    "nome": "Dr. Eduardo Martins Costa",
    "data_nascimento": "1975-01-01",
    "endereco": "Rua General Osório, 500 - Centro Médico",
    "crm": "CRM10001"
}

### lista médico específico
GET {{baseURL}}/lista/4
Authorization: Bearer {{token}}