@baseURL=http://localhost:3000/auth/login
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVuY2FvIjoiQWRtaW4iLCJpYXQiOjE3Nzg1MDIzNDAsImV4cCI6MTc3ODUwNTk0MH0.DnGo-6zcacF62c4f3QsBHS-adnCERNrnGSWfQSbvfz8

### login admin
POST {{baseURL}}
Content-Type: application/json

{
    "cpf":"06589474001",
    "senha":"senha123"
}

### login atendente
POST {{baseURL}}
Content-Type: application/json

{
    "cpf":"96145395001",
    "senha":"senha123"
}

### login médico
POST {{baseURL}}
Content-Type: application/json

{
    "cpf":"03209484040",
    "senha":"senha123"
}