@login=http://localhost:3000/auth/login
@pessoa=http://localhost:3000/pessoas
@tokenAdmin=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVuY2FvIjoiQWRtaW4iLCJpYXQiOjE3Nzg5NzQ1MTgsImV4cCI6MTc3ODk3ODExOH0.jpHuMm0UZ6eXLyTEL7KZkZw3HEZVyevCAQaHSMtRPl8
@tokenPaciente=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZnVuY2FvIjoiUGFjaWVudGUiLCJpYXQiOjE3Nzg5NzU2NDQsImV4cCI6MTc3ODk3OTI0NH0.fY6ea2RktnSnDJPRSmDXuyyBpwwtvmoS_Re2GCcLJVk

### login admin
POST {{login}}
Content-Type: application/json

{"cpf":"06589474001","senha":"senha123"}

### login paciente
POST {{login}}
Content-Type: application/json

{"cpf":"00482581050","senha":"senha123"}

### cria atendente
POST {{pessoa}}/incluir
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
    "cpf": "41336691000",
    "nome": "Luciana Montenegro",
    "data_nascimento": "1989-11-21",
    "telefone": "88982344310",
    "endereco": "Rua das Girafas, 1146 - Tempestade",
    "senha": "senha123",
    "funcao": "Atendente"
}

### paciente NÃO lista usuários
GET {{pessoa}}/lista
Authorization: Bearer {{tokenPaciente}}

### admin lista admins
GET {{pessoa}}/lista?funcao=Admin
Authorization: Bearer {{tokenAdmin}}
