@baseURL=http://localhost:3000

### lista pessoas
GET {{baseURL}}/lista

### criar pessoa
POST {{baseURL}}/incluir
Content-Type: application/json

{
    "cpf":"52998224725",
    "nome":"João da Silva",
    "data":"2000-01-01",
    "telefone":"54 1234-1234",
    "endereco":"Rua A, 120",
    "senha":"abc"
}

### atualizar pessoa
POST {{baseURL}}/atualizar
Content-Type: application/json

{
    "id":2,
    "cpf":"993.998.750-16",
    "nome":"Maria da Silva",
    "data":"2002-02-02",
    "telefone":"54 4321-4321",
    "endereco":"Rua B, 210",
    "senha":"bca"
}

### atualizar pessoa
POST {{baseURL}}/atualizar
Content-Type: application/json

{
    "id":2,
    "cpf":"52998224725",
    "nome":"João da Silva",
    "data":"2000-01-01",
    "telefone":"54 1234-1234",
    "endereco":"Rua A, 120",
    "senha":"abc"
}

### mostra pessoa específica
GET {{baseURL}}/lista/2

### ativar pessoa
POST {{baseURL}}/ativar/2

### desativar pessoa
POST {{baseURL}}/desativar/2