@baseURL=http://localhost:3000/pessoas
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVuY2FvIjoiQWRtaW4iLCJpYXQiOjE3Nzg0Njk4NTUsImV4cCI6MTc3ODQ3MzQ1NX0.uz2mc6HKyLD_jF2HCWKJMLRFKPmLUSSv3W9BtkPQEcQ

### lista pessoas
GET {{baseURL}}/lista
Authorization: Bearer {{token}}

### mostra pessoa específica (atendente)
GET {{baseURL}}/lista/2
Authorization: Bearer {{token}}

### ativar pessoa
PUT {{baseURL}}/ativar/2
Authorization: Bearer {{token}}

### desativar pessoa
PUT {{baseURL}}/desativar/2
Authorization: Bearer {{token}}

### criar pessoa
POST {{baseURL}}/incluir
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cpf":"46809872000",
    "nome":"João da Silva",
    "data":"1980-01-01",
    "telefone":"51990000001",
    "endereco":"Rua Assis Brasil, 120",
    "senha":"senha123",
    "funcao":"Atendente"
}

### atualizar pessoa
PUT {{baseURL}}/atualizar/10
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cpf":"11229077022",
    "nome":"Maria da Silva",
    "data":"1980-01-01",
    "telefone":"51990000001",
    "endereco":"Rua Assis de Brasil, 120",
    "senha":"pwd321"
}

### atualizar pessoa
PUT {{baseURL}}/atualizar/10
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cpf":"46809872000",
    "nome":"João da Silva",
    "data":"1980-01-01",
    "telefone":"51990000001",
    "endereco":"Rua Assis Brasil, 120",
    "senha":"senha123"
}